import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";
// app/layout.js or pages/_app.js (depending on your structure)
import { Dancing_Script } from "next/font/google";

const dancingScript = Dancing_Script({
    subsets: ["latin"],
    weight: ["400", "700"], // Or any weight you need
    variable: "--font-dancing-script", // Optional: for CSS variable use
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body>
                <Navbar />
                <div>{children}</div>
                <Footer />
            </body>
        </html>
    );
}
